services:
  app:
    build: .
    container_name: wb_irrigation_app
    environment:
      - TESTING=0
      - UI_THEME=auto
      - SECRET_KEY=${SECRET_KEY:-wb-irrigation-secret}
    ports:
      - "8080:8080"
    volumes:
      - ./static/media:/app/static/media
      - ./backups:/app/backups
      - ./irrigation.db:/app/irrigation.db
    depends_on:
      - mqtt
    restart: unless-stopped

  mqtt:
    image: eclipse-mosquitto:2
    container_name: wb_irrigation_mqtt
    ports:
      - "1884:1883" # host 1883 busy; use 1884 on host
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./mosquitto_data:/mosquitto/data
      - ./mosquitto_log:/mosquitto/log
    restart: unless-stopped

volumes: {}


